version: '3.8'

services:
  rose:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: RoseFramework
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
